import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import { CartProvider } from "./context/CartContext";
import { Toaster } from "sonner"; // 👈 import Sonner

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistMono.className}>
        <CartProvider>
          <div className="flex flex-col min-h-screen">
            {/* Header at the top */}
            <Header />

            {/* Page content */}
            <main className="flex-1">{children}</main>

            {/* Footer */}
            <footer className="py-6 text-center text-sm text-gray-500 border-t">
              © {new Date().getFullYear()} Infinite Loops. All rights reserved.
            </footer>
          </div>
          <Toaster richColors position="bottom-right" />
        </CartProvider>
      </body>
    </html>
  );
}
